from alpine:latest

LABEL maintainer: zhengqiang99@126.com

ARG SALT_VER=latest

EXPOSE 4505 4506 8041 8042 8043 8044
RUN apk --no-cache add git gcc g++ python3 python3-dev  linux-headers curl --update && \
    mkdir -p /etc/supervisor.d /home/saltops /run && \
    adduser -S salt && echo "salt:salt2018" | chpasswd  && \
    git clone https://gitee.com/wuwenhao/saltops.git /home/saltops  
WORKDIR /home/saltops   
ADD run.sh /run/run.sh 
RUN  rm db.sqlite3 && pip3 --no-cache-dir  install -r requirements.txt &&   \
     python3 manage.py makemigrations && python3 manage.py migrate && \
     echo "#!/bin/sh" >> /docker-entrypoint.sh  && chmod uo+x /docker-entrypoint.sh &&  \
     echo "source /run/sun.sh" && \ 
     echo "cd /home/saltops" >>/docker-entrypoint.sh  && \
     echo "python3 manage.py runserver  0.0.0.0:80 " >> /docker-entrypoint.sh    && \ 
     apk del git gcc g++ python3-dev linux-headers curl 

ENTRYPOINT /docker-entrypoint.sh

HEALTHCHECK --interval=1m --timeout=3s cmd python3 --version || exit 1
